/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://tvptrfhgdncsfk5ml3tgi5cefi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wen3v5flj5csbd2aoapdyniege",
    "aws_cognito_identity_pool_id": "us-east-1:c7ef2b16-c3df-4f46-afb7-df41d21f382e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VNXqrrZmd",
    "aws_user_pools_web_client_id": "458bnkovnt8jucugr5vlqk0nh1",
    "oauth": {
        "domain": "escapeoutvite0e85f0e5-0e85f0e5-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:5173/,https://dev.play.escapeout.games/",
        "redirectSignOut": "http://localhost:5173/,https://dev.play.escapeout.games/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "escapeoutbucket2183723-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "GameMap-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "GameMap-dev"
            }
        }
    }
};


export default awsmobile;
